import { Language, Translations, RuleStep } from './types';

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    home: "Home",
    play: "Play",
    learn: "Learn",
    customize: "Custom",
    credits: "Credits",
    playNow: "Play Now",
    howToPlay: "How to Play",
    heroTitle: "Ting-Ting",
    heroSubtitle: "Experience the magic of the playground anywhere.",
    rulesHeader: "Master the Hop",
    creditsTitle: "Credits",
    creditsSubtitle: "Developed by Group 15 T1 from Faculty of Computer Science & Information Technology, University Malaya",
    feature1Title: "Digital Playground",
    feature1Desc: "Interactive chalkboards and boards to practice your moves safely.",
    feature2Title: "Multi-language",
    feature2Desc: "Learn the rules in your native tongue with our global selector.",
    feature3Title: "Fully Customizable",
    feature3Desc: "Choose your chalk colors and special markers to play your way.",
    customizeHeader: "Customize Your Game",
    paletteHeader: "Chalk Palette",
    paletteDesc: "Changing your chalk color updates the highlights across the entire app interface.",
    markerHeader: "Lucky Marker",
    characterHeader: "Character Studio",
    genderHeader: "Pick a Hero",
    styleHeader: "Outfit Style",
    readyTitle: "Ready to Play?",
    readyDesc: "Your new style is saved! Head over to the board and start hopping.",
    goToGame: "Go to Game",
    activeLabel: "Active",
    markerStone: "Magic Stone",
    markerShell: "Beach Shell",
    markerCoin: "Lucky Coin",
    markerHouse: "Traditional House",
    boyLabel: "Boy",
    girlLabel: "Girl",
    styleCasual: "Casual",
    styleSporty: "Sporty",
    styleFancy: "Fancy",
    specialThanks: "Special Thanks",
    thanksTags: ["Street Chalk Inc.", "Summer Camps 2024", "Sidewalk Guild", "Old School Games"],
    creditsFooter: "Hopscotch is a timeless tradition spanning centuries. This app is a love letter to the simple joy of physical play.",
    roleCreative: "Creative Director",
    roleLead: "Lead Developer",
    roleUX: "UX Strategist",
    roleMotion: "Motion Designer",
    roleTranslator: "Translator",
    roleBeta: "Beta Testers",
    roleAdvisor: "Advisor",
    stepLabel: "Step",
    proTipTitle: "Pro Tip!",
    proTipDesc: "Always focus on a spot about two steps ahead of you when hopping. This helps maintain balance!",
    score: "Score",
    level: "Level",
    lives: "Lives",
    phaseThrowing: "Throwing",
    phaseHopping: "Hopping Out",
    phaseBack: "Hopping Back",
    phasePick: "Picking Up",
    phaseClear: "Round Clear!",
    balanced: "Balanced! Hop Now! ✨",
    wait: "Wait for Green! ⚖️",
    gameOver: "GAME OVER",
    tryAgain: "TRY AGAIN",
    champion: "CHAMPION!",
    totalPoints: "Total Points",
    missedThrow: "MISSED THROW! 🎯",
    lostBalance: "LOST BALANCE! ⚖️",
    steppedMarker: "STEPPED ON MARKER! 🚫",
    steppedOutside: "STEPPED OUTSIDE! 🚫",
    wrongBox: "WRONG BOX! 🚫",
    footerNote: "Built with joy for playgrounds everywhere.",
    balanceSafe: "SAFE ZONE",
    balanceUnsafe: "DANGER"
  },
  ms: {
    home: "Utama",
    play: "Main",
    learn: "Belajar",
    customize: "Ubah Suai",
    credits: "Penghargaan",
    playNow: "Main Sekarang",
    howToPlay: "Cara Bermain",
    heroTitle: "Ting-Ting",
    heroSubtitle: "Alami keajaiban taman permainan di mana-mana sahaja.",
    rulesHeader: "Kuasai Lompatan",
    creditsTitle: "Penghargaan",
    creditsSubtitle: "Dibangunkan oleh Kumpulan 15 T1 dari Fakulti Sains Komputer & Teknologi Maklumat, Universiti Malaya",
    feature1Title: "Taman Permainan Digital",
    feature1Desc: "Papan kapur interaktif untuk berlatih pergerakan anda dengan selamat.",
    feature2Title: "Pelbagai Bahasa",
    feature2Desc: "Pelajari peraturan dalam bahasa ibunda anda dengan pemilih global kami.",
    feature3Title: "Boleh Diubah Suai",
    feature3Desc: "Pilih warna kapur dan penanda khas untuk bermain mengikut gaya anda.",
    customizeHeader: "Ubah Suai Permainan Anda",
    paletteHeader: "Palet Kapur",
    paletteDesc: "Menukar warna kapur akan mengemas kini sorotan di seluruh antara muka aplikasi.",
    markerHeader: "Penanda Tuah",
    characterHeader: "Studio Karakter",
    genderHeader: "Pilih Hero",
    styleHeader: "Gaya Pakaian",
    readyTitle: "Sedia untuk Bermain?",
    readyDesc: "Gaya baharu anda telah disimpan! Pergi ke papan dan mula melompat.",
    goToGame: "Ke Permainan",
    activeLabel: "Aktif",
    markerStone: "Batu Ajaib",
    markerShell: "Kerang Pantai",
    markerCoin: "Syiling Tuah",
    markerHouse: "Rumah Tradisional",
    boyLabel: "Lelaki",
    girlLabel: "Perempuan",
    styleCasual: "Biasa",
    styleSporty: "Sukan",
    styleFancy: "Mewah",
    specialThanks: "Terima Kasih Khas",
    thanksTags: ["Syarikat Kapur Jalanan", "Kem Musim Panas 2024", "Kesatuan Kaki Lima", "Permainan Sekolah Lama"],
    creditsFooter: "Ting-Ting adalah tradisi abadi merentasi berabad-abad. Aplikasi ini adalah surat cinta kepada kegembiraan ringkas bermain fizikal.",
    roleCreative: "Pengarah Kreatif",
    roleLead: "Ketua Pembangun",
    roleUX: "Pakar Strategi UX",
    roleMotion: "Pereka Gerakan",
    roleTranslator: "Penterjemah",
    roleBeta: "Penguji Beta",
    roleAdvisor: "Penasihat",
    stepLabel: "Langkah",
    proTipTitle: "Tip Pro!",
    proTipDesc: "Sentiasa fokus pada tempat kira-kira dua langkah di hadapan anda semasa melompat. Ini membantu imbangan!",
    score: "Skor",
    level: "Tahap",
    lives: "Nyawa",
    phaseThrowing: "Membaling",
    phaseHopping: "Melompat Keluar",
    phaseBack: "Melompat Balik",
    phasePick: "Mengambil",
    phaseClear: "Tahap Selesai! 🎉",
    balanced: "Seimbang! Lompat! ✨",
    wait: "Tunggu Hijau! ⚖️",
    gameOver: "TAMAT PERMAINAN",
    tryAgain: "CUBA LAGI",
    champion: "JUARA!",
    totalPoints: "Jumlah Mata",
    missedThrow: "BALINGAN Sipi! 🎯",
    lostBalance: "HILANG IMBANGAN! ⚖️",
    steppedMarker: "PIJAK PENANDA! 🚫",
    steppedOutside: "PIJAK LUAR! 🚫",
    wrongBox: "KOTAK SALAH! 🚫",
    footerNote: "Dibina dengan kegembiraan untuk taman permainan di mana-mana sahaja.",
    balanceSafe: "ZON SELAMAT",
    balanceUnsafe: "BAHAYA"
  },
  zh: {
    home: "首页",
    play: "开始",
    learn: "规则",
    customize: "设置",
    credits: "致谢",
    playNow: "立即玩",
    howToPlay: "如何玩",
    heroTitle: "跳房子",
    heroSubtitle: "随时随地体验游乐场的魔力。",
    rulesHeader: "掌握跳跃",
    creditsTitle: "制作团队",
    creditsSubtitle: "由马来亚大学计算机科学与信息技术学院 Group 15 T1 开发",
    feature1Title: "数字游乐场",
    feature1Desc: "互动式黑板和板子，安全练习您的动作。",
    feature2Title: "多语言支持",
    feature2Desc: "通过我们的全球选择器以您的母语学习规则。",
    feature3Title: "完全可定制",
    feature3Desc: "选择您的粉笔颜色和特殊标记，以您的方式玩游戏。",
    customizeHeader: "自定义您的游戏",
    paletteHeader: "粉笔色盘",
    paletteDesc: "更改粉笔颜色将更新整个应用程序界面的高亮显示。",
    markerHeader: "幸运标记",
    characterHeader: "角色工坊",
    genderHeader: "选择主角",
    styleHeader: "服装风格",
    readyTitle: "准备好玩了吗？",
    readyDesc: "您的新风格已保存！前往棋盘开始跳跃吧。",
    goToGame: "进入游戏",
    activeLabel: "生效中",
    markerStone: "魔力石",
    markerShell: "海滩贝壳",
    markerCoin: "幸运币",
    markerHouse: "传统住宅",
    boyLabel: "男生",
    girlLabel: "女生",
    styleCasual: "休闲",
    styleSporty: "运动",
    styleFancy: "华丽",
    specialThanks: "特别感谢",
    thanksTags: ["街头粉笔公司", "2024夏令营", "人行道公会", "老派游戏"],
    creditsFooter: "跳房子是一项跨越数世纪的永恒传统。这个应用程序是写给简单身体游戏乐趣的一封情书。",
    roleCreative: "创意总监",
    roleLead: "首席开发人员",
    roleUX: "UX 战略家",
    roleMotion: "动作设计师",
    roleTranslator: "翻译",
    roleBeta: "测试员",
    roleAdvisor: "顾问",
    stepLabel: "步骤",
    proTipTitle: "专业提示！",
    proTipDesc: "跳跃时始终注视前方约两步的位置。这有助于保持平衡！",
    score: "分数",
    level: "等级",
    lives: "生命",
    phaseThrowing: "投掷",
    phaseHopping: "跳出",
    phaseBack: "跳回",
    phasePick: "捡起",
    phaseClear: "通关！🎉",
    balanced: "平衡！快跳！✨",
    wait: "等待绿色！⚖️",
    gameOver: "游戏结束",
    tryAgain: "再试一次",
    champion: "冠军！",
    totalPoints: "总分",
    missedThrow: "投掷未中！🎯",
    lostBalance: "失去平衡！⚖️",
    steppedMarker: "踩到标记！🚫",
    steppedOutside: "踩到线外！🚫",
    wrongBox: "盒子错误！🚫",
    footerNote: "为各地的游乐场倾情打造。",
    balanceSafe: "安全区",
    balanceUnsafe: "危险"
  },
  ta: {
    home: "முகப்பு",
    play: "விளையாடு",
    learn: "கற்றல்",
    customize: "மாற்று",
    credits: "குழு",
    playNow: "விளையாடு",
    howToPlay: "முறை",
    heroTitle: "டிங்-டிங்",
    heroSubtitle: "விளையாட்டு மைதானத்தின் மாயாஜாலத்தை எங்கும் அனுபவியுங்கள்.",
    rulesHeader: "குதிப்பதில் தேர்ச்சி",
    creditsTitle: "படைப்பாளர்கள்",
    creditsSubtitle: "மலாயா பல்கலைக்கழகத்தின் கணினி அறிவியல் மற்றும் தகவல் தொழில்நுட்ப பீடத்தின் குரூப் 15 T1 ஆல் உருவாக்கப்பட்டது",
    feature1Title: "டிஜிட்டல் விளையாட்டு மைதானம்",
    feature1Desc: "உங்கள் அசைவுகளைப் பாதுகாப்பாகப் பயிற்சி செய்ய ஊடாடும் பலகைகள்.",
    feature2Title: "பல மொழிகள்",
    feature2Desc: "எங்கள் உலகளாவிய தேர்வாளர் மூலம் உங்கள் தாய்மொழியில் விதிகளைக் கற்றுக்கொள்ளுங்கள்.",
    feature3Title: "முழுமையாக மாற்றக்கூடியது",
    feature3Desc: "உங்கள் வழியில் விளையாட உங்கள் சுண்ணாம்பு வண்ணங்களையும் அடையாளங்களையும் தேர்வு செய்யவும்.",
    customizeHeader: "உங்கள் விளையாட்டை மாற்றியமைக்கவும்",
    paletteHeader: "சுண்ணாம்புத் தட்டு",
    paletteDesc: "உங்கள் சுண்ணாம்பு நிறத்தை மாற்றுவது சிறப்பம்சங்களைப் புதுப்பிக்கும்.",
    markerHeader: "அதிர்ஷ்ட அடையாளம்",
    characterHeader: "கதாபாத்திர ஸ்டுடியோ",
    genderHeader: "நாயகனைத் தேர்ந்தெடு",
    styleHeader: "உடை பாணி",
    readyTitle: "விளையாடத் தயாரா?",
    readyDesc: "உங்கள் புதிய நடை சேமிக்கப்பட்டது! பலகைக்குச் சென்று குதிக்கத் தொடங்குங்கள்.",
    goToGame: "விளையாட்டிற்குச் செல்லவும்",
    activeLabel: "செயலில் உள்ளது",
    markerStone: "மந்திரக் கல்",
    markerShell: "கடல் கிளிஞ்சல்",
    markerCoin: "அதிர்ஷ்ட நாணயம்",
    markerHouse: "பாரம்பரிய வீடு",
    boyLabel: "ஆண்",
    girlLabel: "பெண்",
    styleCasual: "இயல்பு",
    styleSporty: "விளையாட்டு",
    styleFancy: "ஆடம்பரம்",
    specialThanks: "சிறப்பு நன்றிகள்",
    thanksTags: ["சுண்ணாம்பு நிறுவனம்", "கோடைகால முகாம் 2024", "நடைபாதை சங்கம்", "பழைய விளையாட்டுகள்"],
    creditsFooter: "நொண்டி விளையாட்டு ஒரு காலமற்ற பாரம்பரியமாகும். இந்த பயன்பாடு விளையாட்டின் மகிழ்ச்சிக்கான ஒரு காதல் கடிதம்.",
    roleCreative: "படைப்பு இயக்குநர்",
    roleLead: "தலைமை உருவாக்குநர்",
    roleUX: "UX நிபுணர்",
    roleMotion: "மோஷன் டிசைனர்",
    roleTranslator: "மொழிபெயர்ப்பாளர்",
    roleBeta: "பீட்டா சோதனையாளர்கள்",
    roleAdvisor: "ஆலோசகர்",
    stepLabel: "படி",
    proTipTitle: "சிறப்பு குறிப்பு!",
    proTipDesc: "குதிக்கும் போது எப்போதும் உங்களுக்கு முன்னால் இரண்டு படிகள் தூரத்தில் கவனம் செலுத்துங்கள். இது சமநிலைக்கு உதவும்!",
    score: "மதிப்பெண்",
    level: "நிலை",
    lives: "உயிர்கள்",
    phaseThrowing: "எறிதல்",
    phaseHopping: "குதித்தல்",
    phaseBack: "திரும்புதல்",
    phasePick: "எடுத்தல்",
    phaseClear: "வெற்றி! 🎉",
    balanced: "சமநிலை! குதிக்கவும்! ✨",
    wait: "காத்திருக்கவும்! ⚖️",
    gameOver: "ஆட்டம் முடிந்தது",
    tryAgain: "மீண்டும் முயல்க",
    champion: "சாмпயன்!",
    totalPoints: "மொத்த மதிப்பெண்",
    missedThrow: "தவறிய எறிதல்! 🎯",
    lostBalance: "சமநிலை தவறியது! ⚖️",
    steppedMarker: "அடையாளத்தில் மிதித்தீர்கள்! 🚫",
    steppedOutside: "வெளியே மிதித்தீர்கள்! 🚫",
    wrongBox: "தவறான பெட்டி! 🚫",
    footerNote: "விளையாட்டு மைதானங்களுக்காக மகிழ்ச்சியுடன் உருவாக்கப்பட்டது.",
    balanceSafe: "பாதுகாப்பான பகுதி",
    balanceUnsafe: "ஆபத்து"
  }
};

export const HOPSCOTCH_RULES: Record<Language, RuleStep[]> = {
  en: [
    { number: 1, text: "Throw your marker into the target box (starting with Box 1).", icon: "🎯" },
    { number: 2, text: "Hop on one foot in single boxes and two feet in double boxes.", icon: "👟" },
    { number: 3, text: "ALWAYS skip the box that has the marker in it!", icon: "🚫" },
    { number: 4, text: "Reach the end (Box 10), turn around, and head back.", icon: "🔄" },
    { number: 5, text: "Stop at the box before the marker and pick it up.", icon: "💎" },
    { number: 6, text: "Complete the hop to progress to the next level!", icon: "📈" }
  ],
  ms: [
    { number: 1, text: "Baling penanda anda ke dalam kotak sasaran (bermula dengan Kotak 1).", icon: "🎯" },
    { number: 2, text: "Lompat dengan satu kaki di kotak tunggal dan dua kaki di kotak berkembar.", icon: "👟" },
    { number: 3, text: "SENTIASA langkau kotak yang mempunyai penanda di dalamnya!", icon: "🚫" },
    { number: 4, text: "Sampai ke penghujung (Kotak 10), pusing balik, dan tuju ke mula.", icon: "🔄" },
    { number: 5, text: "Berhenti di kotak sebelum penanda dan ambil ia.", icon: "💎" },
    { number: 6, text: "Lengkapkan lompatan untuk mara ke tahap seterusnya!", icon: "📈" }
  ],
  zh: [
    { number: 1, text: "将你的标记投进目标方格（从1号格开始）。", icon: "🎯" },
    { number: 2, text: "单格单脚跳，双格双脚跳。", icon: "👟" },
    { number: 3, text: "务必跳过有标记所在的那个方格！", icon: "🚫" },
    { number: 4, text: "到达终点（10号格），转身原路返回。", icon: "🔄" },
    { number: 5, text: "在标记前的方格停下并捡起标记。", icon: "💎" },
    { number: 6, text: "完成整个跳跃过程即可进入下一关！", icon: "📈" }
  ],
  ta: [
    { number: 1, text: "உங்கள் அடையாளத்தை இலக்கு பெட்டிக்குள் எறியுங்கள் (பெட்டி 1 இல் தொடங்குகிறது).", icon: "🎯" },
    { number: 2, text: "ஒற்றை பெட்டிகளில் ஒரு காலிலும், இரட்டை பெட்டிகளில் இரண்டு கால்களிலும் குதிக்கவும்.", icon: "👟" },
    { number: 3, text: "அடையாளம் உள்ள பெட்டியை எப்போதும் தவிர்க்கவும்!", icon: "🚫" },
    { number: 4, text: "இறுதி பெட்டியை (பெட்டி 10) அடைந்து, திரும்பி வரவும்.", icon: "🔄" },
    { number: 5, text: "அடையாளத்திற்கு முந்தைய பெட்டியில் நின்று அதை எடுக்கவும்.", icon: "💎" },
    { number: 6, text: "அடுத்த நிலைக்குச் செல்ல குதித்து முடிக்கவும்!", icon: "📈" }
  ]
};

export const COLORS = [
  { name: 'Sky Blue', hex: '#60a5fa' },
  { name: 'Peach', hex: '#fb923c' },
  { name: 'Mint', hex: '#4ade80' },
  { name: 'Lavender', hex: '#a78bfa' },
  { name: 'Rose', hex: '#fb7185' }
];

export const MARKERS = [
  { id: 'house', emoji: '🛖', labelKey: 'markerHouse' },
  { id: 'stone', emoji: '🪨', labelKey: 'markerStone' },
  { id: 'shell', emoji: '🐚', labelKey: 'markerShell' },
  { id: 'coin', emoji: '🪙', labelKey: 'markerCoin' }
];

export const CHARACTER_TYPES = [
  { id: 'boy', labelKey: 'boyLabel', icon: '👦' },
  { id: 'girl', labelKey: 'girlLabel', icon: '👧' }
];

export const CHARACTER_STYLES = [
  { id: 'casual', labelKey: 'styleCasual', icon: '👕' },
  { id: 'sporty', labelKey: 'styleSporty', icon: '🏃' },
  { id: 'fancy', labelKey: 'styleFancy', icon: '✨' }
];